apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  #Config for DB, Express, object storage
  postgres-db: "collabspace"
  postgres-user: "postgres"
  spaces-endpoint: "https://tor1.digitaloceanspaces.com"
  spaces-bucket: "collabspacebuckets"
  spaces-region: "tor1"
  collab-port: "6001"
  express-port: "5000"
  frontend-url: "http://152.42.146.198" #for cors
  
  #Config for frontend
  react-app-api-url: "http://152.42.146.198/api"
  react-app-collab-socket: "ws://152.42.146.198/collab"